/**
 * Ensures ISO country rows exist in `region_country` so Admin can attach them to regions.
 * Without these rows, saving a region with e.g. "us" fails with:
 *   Countries with codes: "us" do not exist
 *
 * Run from unifiedcommerce-store:
 *   npx medusa exec ./src/scripts/seed-region-countries.ts
 */
import { ExecArgs } from "@medusajs/framework/types"
import { ContainerRegistrationKeys, Modules } from "@medusajs/framework/utils"

/** ISO 3166-1 alpha-2, alpha-3, numeric, English short + display names (Medusa region_country schema). */
const COUNTRIES: Array<{
  iso_2: string
  iso_3: string
  num_code: string
  name: string
  display_name: string
}> = [
  { iso_2: "us", iso_3: "usa", num_code: "840", name: "UNITED STATES", display_name: "United States" },
  { iso_2: "ca", iso_3: "can", num_code: "124", name: "CANADA", display_name: "Canada" },
  { iso_2: "mx", iso_3: "mex", num_code: "484", name: "MEXICO", display_name: "Mexico" },
  { iso_2: "gb", iso_3: "gbr", num_code: "826", name: "UNITED KINGDOM", display_name: "United Kingdom" },
  { iso_2: "de", iso_3: "deu", num_code: "276", name: "GERMANY", display_name: "Germany" },
  { iso_2: "fr", iso_3: "fra", num_code: "250", name: "FRANCE", display_name: "France" },
  { iso_2: "es", iso_3: "esp", num_code: "724", name: "SPAIN", display_name: "Spain" },
  { iso_2: "it", iso_3: "ita", num_code: "380", name: "ITALY", display_name: "Italy" },
  { iso_2: "nl", iso_3: "nld", num_code: "528", name: "NETHERLANDS", display_name: "Netherlands" },
  { iso_2: "be", iso_3: "bel", num_code: "056", name: "BELGIUM", display_name: "Belgium" },
  { iso_2: "at", iso_3: "aut", num_code: "040", name: "AUSTRIA", display_name: "Austria" },
  { iso_2: "ch", iso_3: "che", num_code: "756", name: "SWITZERLAND", display_name: "Switzerland" },
  { iso_2: "ie", iso_3: "irl", num_code: "372", name: "IRELAND", display_name: "Ireland" },
  { iso_2: "se", iso_3: "swe", num_code: "752", name: "SWEDEN", display_name: "Sweden" },
  { iso_2: "no", iso_3: "nor", num_code: "578", name: "NORWAY", display_name: "Norway" },
  { iso_2: "dk", iso_3: "dnk", num_code: "208", name: "DENMARK", display_name: "Denmark" },
  { iso_2: "fi", iso_3: "fin", num_code: "246", name: "FINLAND", display_name: "Finland" },
  { iso_2: "pl", iso_3: "pol", num_code: "616", name: "POLAND", display_name: "Poland" },
  { iso_2: "au", iso_3: "aus", num_code: "036", name: "AUSTRALIA", display_name: "Australia" },
  { iso_2: "nz", iso_3: "nzl", num_code: "554", name: "NEW ZEALAND", display_name: "New Zealand" },
  { iso_2: "jp", iso_3: "jpn", num_code: "392", name: "JAPAN", display_name: "Japan" },
  { iso_2: "kr", iso_3: "kor", num_code: "410", name: "KOREA, REPUBLIC OF", display_name: "South Korea" },
  { iso_2: "sg", iso_3: "sgp", num_code: "702", name: "SINGAPORE", display_name: "Singapore" },
  { iso_2: "in", iso_3: "ind", num_code: "356", name: "INDIA", display_name: "India" },
  { iso_2: "br", iso_3: "bra", num_code: "076", name: "BRAZIL", display_name: "Brazil" },
]

type RegionModuleWithCountries = {
  listCountries: (
    filters: { iso_2: string[] },
    config?: { take?: number }
  ) => Promise<{ iso_2: string }[]>
  /** Generated by MedusaService (Country model); not on public interface typings. */
  createCountries: (data: unknown | unknown[]) => Promise<unknown>
}

export default async function seedRegionCountries({ container }: ExecArgs) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER) as { info: (m: string) => void; warn: (m: string) => void }
  const regionModule = container.resolve(Modules.REGION) as RegionModuleWithCountries

  const existing = await regionModule.listCountries(
    { iso_2: COUNTRIES.map((c) => c.iso_2) },
    { take: COUNTRIES.length + 50 }
  )
  const have = new Set(existing.map((e) => (e.iso_2 || "").toLowerCase()))
  const missing = COUNTRIES.filter((c) => !have.has(c.iso_2.toLowerCase()))

  if (missing.length === 0) {
    logger.info(`[seed-region-countries] All ${COUNTRIES.length} reference countries already present. Nothing to do.`)
    return
  }

  logger.info(`[seed-region-countries] Creating ${missing.length} missing country row(s): ${missing.map((m) => m.iso_2).join(", ")}`)

  await regionModule.createCountries(missing)

  logger.info("[seed-region-countries] Done. You can attach these ISO codes to regions in Medusa Admin.")
}
