/**
 * 100 grocery item names per category for seed data (800 total).
 * Used to build full templates with default options and descriptions.
 */

const PRODUCE_100: string[] = [
  "Organic Gala Apples", "Fuji Apples", "Granny Smith Apples", "Honeycrisp Apples", "Bananas",
  "Navel Oranges", "Valencia Oranges", "Lemons", "Limes", "Red Seedless Grapes", "Green Grapes",
  "Strawberries", "Blueberries", "Raspberries", "Blackberries", "Watermelon", "Cantaloupe",
  "Honeydew Melon", "Pineapple", "Mango", "Avocado", "Kiwi", "Peaches", "Nectarines", "Plums",
  "Anjou Pears", "Bartlett Pears", "Pomegranate", "Green Cabbage", "Red Cabbage", "Broccoli",
  "Cauliflower", "Carrots", "Celery", "Cucumber", "Red Bell Peppers", "Green Bell Peppers",
  "Yellow Bell Peppers", "Orange Bell Peppers", "Baby Spinach", "Kale", "Romaine Lettuce",
  "Iceberg Lettuce", "Mixed Salad Greens", "Yellow Onions", "Red Onions", "Sweet Onions",
  "Garlic", "Russet Potatoes", "Red Potatoes", "Sweet Potatoes", "Yukon Gold Potatoes",
  "Roma Tomatoes", "Cherry Tomatoes", "Beefsteak Tomatoes", "Grape Tomatoes", "Zucchini",
  "Yellow Squash", "Butternut Squash", "Acorn Squash", "Green Beans", "Snow Peas", "Sugar Snap Peas",
  "Corn on the Cob", "White Mushrooms", "Cremini Mushrooms", "Shiitake Mushrooms", "Asparagus",
  "Radishes", "Beets", "Turnips", "Parsnips", "Brussels Sprouts", "Eggplant", "Bok Choy",
  "Collard Greens", "Swiss Chard", "Leeks", "Shallots", "Fresh Ginger", "Fresh Basil",
  "Fresh Cilantro", "Fresh Parsley", "Fresh Dill", "Fresh Mint", "Fresh Rosemary", "Fresh Thyme",
  "Key Limes", "Tangerines", "Clementines", "Papaya", "Dragon Fruit", "Persimmon", "Fresh Figs",
  "Medjool Dates", "Young Coconut", "Fresh Cranberries", "Rhubarb", "Okra", "Artichokes",
  "Jicama", "Water Chestnuts", "Baby Carrots", "Broccolini", "Romanesco", "Endive", "Arugula",
  "Frisee", "Escarole", "Watercress", "Dandelion Greens", "Mustard Greens", "Kohlrabi", "Rutabaga",
  "Daikon Radish", "Celery Root", "Sunchokes", "Fennel Bulb", "Green Cabbage Head", "Napa Cabbage",
  "Bok Choy Baby", "Tatsoi", "Mizuna", "Microgreens", "Edamame Fresh", "Sugar Snap Peas Fresh",
  "English Peas", "Wax Beans", "Romano Beans", "Habanero", "Serrano Peppers", "Poblano Peppers",
  "Anaheim Peppers", "Jalapeño", "Thai Chili", "Fingerling Potatoes", "Purple Potatoes",
];

function padTo100(arr: string[], category: string): string[] {
  if (arr.length >= 100) return arr.slice(0, 100);
  const out = [...arr];
  while (out.length < 100) out.push(`Assorted ${category} Item ${out.length + 1}`);
  return out;
}

const DAIRY_EGGS_100: string[] = [
  "Whole Milk", "2% Reduced Fat Milk", "Skim Milk", "Half and Half", "Heavy Cream",
  "Salted Butter", "Unsalted Butter", "Large White Eggs", "Large Brown Eggs", "Organic Eggs",
  "Free Range Eggs", "Cheddar Cheese Block", "Mozzarella Cheese", "Parmesan Wedge", "Swiss Cheese",
  "Provolone Slices", "Cream Cheese", "Sour Cream", "Cottage Cheese", "Ricotta Cheese",
  "Plain Greek Yogurt", "Vanilla Greek Yogurt", "Strawberry Yogurt", "Blueberry Yogurt",
  "Plain Yogurt", "String Cheese", "Colby Jack Cheese", "Pepper Jack Cheese", "Monterey Jack",
  "Brie Cheese", "Feta Crumbles", "Goat Cheese", "Blue Cheese", "Gouda", "Havarti",
  "Mascarpone", "Whipped Cream", "Sweetened Condensed Milk", "Evaporated Milk", "Lactose-Free Milk",
  "Chocolate Milk", "Egg Whites", "Liquid Egg Substitute", "Organic Whole Milk",
  "Organic 2% Milk", "Almond Milk Creamer", "Butter Quarters", "European Style Butter",
  "Neufchatel Cheese", "Light Sour Cream", "Lowfat Cottage Cheese", "Kefir Plain",
  "Skyr Yogurt", "Coconut Yogurt", "Smoked Gouda", "Aged Cheddar", "Fresh Mozzarella Ball",
  "Ricotta Salata", "Paneer", "Queso Fresco", "Cotija Cheese", "Oaxaca Cheese",
  "Gruyere", "Fontina", "Manchego", "Havarti with Dill", "Baby Swiss", "Muenster",
  "Extra Sharp Cheddar", "Mild Cheddar Slices", "Colby Cheese", "Velveeta Block",
  "American Cheese Slices", "Cream Cheese Spread", "Honey Greek Yogurt", "Key Lime Yogurt",
  "Vanilla Bean Yogurt", "Lowfat Milk", "Organic Butter", "Grass-Fed Butter",
  "Clarified Butter", "Egg Nog", "Pudding Cups Vanilla", "Flan", "Tres Leches",
  "Dulce de Leche", "Clotted Cream", "Crème Fraîche", "Quark", "Farmer Cheese",
  "Laughing Cow Wedges", "Boursin Cheese", "Pub Cheese", "Pimento Cheese Spread",
  "Nacho Cheese Sauce", "Shredded Cheddar", "Shredded Mozzarella", "Mexican Blend Shredded",
  "Italian Blend Shredded", "Parmesan Shredded", "Colby Jack Shredded",
];

const BEVERAGES_100: string[] = [
  "Orange Juice", "Apple Juice", "Grape Juice", "Cranberry Juice", "Pineapple Juice",
  "Almond Milk", "Oat Milk", "Soy Milk", "Coconut Milk", "Cashew Milk", "Rice Milk",
  "Sparkling Water", "Lemonade", "Iced Tea", "Green Tea", "Black Tea", "Herbal Tea",
  "Cola", "Diet Cola", "Ginger Ale", "Root Beer", "Lemon Lime Soda", "Energy Drink",
  "Sports Drink", "Vitamin Water", "Sparkling Lemonade", "Sparkling Cranberry",
  "Cold Brew Coffee", "Bottled Iced Coffee", "Espresso Beans", "Ground Coffee", "K-Cups",
  "Hot Cocoa Mix", "Chocolate Milk", "Horchata", "Agua Fresca", "Coconut Water",
  "Flavored Seltzer", "Mineral Water", "Spring Water", "Purified Water", "Distilled Water",
  "Fruit Punch", "Grapefruit Juice", "Tomato Juice", "Vegetable Juice", "Smoothie Blend",
  "Protein Shake", "Meal Replacement Shake", "Kombucha", "Probiotic Drink",
  "Matcha Latte", "Chai Concentrate", "Hot Chocolate", "Apple Cider", "Mulled Cider",
  "Prune Juice", "V8 Juice", "Carrot Juice", "Beet Juice", "Celery Juice",
  "Aloe Vera Drink", "Mango Nectar", "Peach Nectar", "Guava Nectar", "Passion Fruit Juice",
  "Pomegranate Juice", "Acai Juice", "Blueberry Juice", "Cherry Juice", "Watermelon Juice",
  "Cucumber Mint Water", "Detox Tea", "Sleepy Time Tea", "Peppermint Tea", "Chamomile Tea",
  "Earl Grey", "English Breakfast", "Decaf Coffee", "Instant Coffee", "Coffee Pods",
  "Nitro Cold Brew", "Latte", "Cappuccino", "Mocha", "Vanilla Creamer", "Hazelnut Creamer",
  "Irish Cream", "Bailey's Style Creamer", "Non-Dairy Creamer", "Sweet Tea",
  "Unsweetened Tea", "Peach Tea", "Raspberry Tea", "Mango Tea", "Bubble Tea Tapioca",
  "Tonic Water", "Club Soda", "Seltzer Water 12 Pack", "LaCroix Variety", "Spindrift",
  "Hint Water", "Bai Antioxidant", "BodyArmor", "Gatorade", "Powerade", "Red Bull",
  "Monster Energy", "Bang Energy", "Rockstar", "5 Hour Energy", "Yerba Mate",
];

const BAKERY_100: string[] = [
  "Sourdough Bread", "White Bread", "Whole Wheat Bread", "Multigrain Bread", "Rye Bread",
  "Bagels Plain", "Cinnamon Raisin Bagels", "Everything Bagels", "Croissants", "Chocolate Croissants",
  "English Muffins", "Whole Wheat Tortillas", "Flour Tortillas", "Corn Tortillas", "Pita Bread",
  "Naan Bread", "Ciabatta", "Baguette", "French Bread", "Italian Bread", "Hawaiian Rolls",
  "Dinner Rolls", "Hot Dog Buns", "Hamburger Buns", "Sub Rolls", "Pizza Dough", "Pie Crust",
  "Muffins Blueberry", "Muffins Chocolate Chip", "Muffins Bran", "Donuts Glazed", "Donuts Chocolate",
  "Donuts Powdered", "Donut Holes", "Cookies Chocolate Chip", "Cookies Oatmeal Raisin",
  "Cookies Sugar", "Brownies", "Blondies", "Coffee Cake", "Cinnamon Rolls", "Danish Pastry",
  "Éclairs", "Cannoli", "Pound Cake", "Angel Food Cake", "Layer Cake", "Cupcakes",
  "Banana Bread", "Zucchini Bread", "Pumpkin Bread", "Cornbread", "Garlic Bread",
  "Breadsticks", "Croutons", "Stuffing Mix", "Panko Breadcrumbs", "Seasoned Breadcrumbs",
  "Flatbread", "Lavash", "Focaccia", "Brioche", "Challah", "Pretzel Buns",
  "Gluten-Free Bread", "Keto Bread", "Low Carb Tortillas", "Wraps Spinach", "Wraps Sundried Tomato",
  "Mini Bagels", "Cream Cheese Bagels", "Apple Fritters", "Bear Claws", "Strudel",
  "Palmiers", "Macarons", "Madeleines", "Biscotti", "Shortbread", "Graham Crackers",
  "Teddy Grahams", "Animal Crackers", "Vanilla Wafers", "Lady Fingers", "Phyllo Dough",
  "Puff Pastry", "Pie Dough", "Tart Shells", "Pizza Crust Thin", "Pizza Crust Thick",
  "Brioche Buns", "Slider Buns", "Texas Toast", "Croutons Caesar", "Melba Toast",
  "Rye Crispbread", "Wasa Crackers", "Rice Cakes", "Matzo", "Tortilla Chips Large",
  "Taco Shells", "Tostada Shells", "Churros", "Conchas", "Pan Dulce", "Baguette Mini",
  "Artisan Loaf", "Farmhouse Bread", "Mountain Bread", "Sprouted Grain Bread",
  "Cinnamon Swirl Bread", "Raisin Bread", "Pumpernickel", "Marble Rye",
];

const PANTRY_100: string[] = [
  "Extra Virgin Olive Oil", "Vegetable Oil", "Canola Oil", "Coconut Oil", "Avocado Oil",
  "All-Purpose Flour", "Bread Flour", "Whole Wheat Flour", "Sugar Granulated", "Brown Sugar",
  "Powdered Sugar", "Honey", "Maple Syrup", "Tomato Paste", "Tomato Sauce", "Crushed Tomatoes",
  "Diced Tomatoes", "Black Beans", "Kidney Beans", "Pinto Beans", "Chickpeas", "Lentils",
  "White Rice", "Brown Rice", "Jasmine Rice", "Basmati Rice", "Quinoa", "Oatmeal", "Cereal",
  "Granola", "Pasta Spaghetti", "Pasta Penne", "Pasta Elbow", "Pasta Fettuccine", "Rice Noodles",
  "Chicken Broth", "Beef Broth", "Vegetable Broth", "Canned Soup", "Peanut Butter",
  "Almond Butter", "Jam Strawberry", "Jam Grape", "Jelly", "Nutella", "Tahini",
  "Soy Sauce", "Hot Sauce", "Vinegar White", "Vinegar Apple Cider", "Vinegar Balsamic",
  "Ketchup", "Mustard Yellow", "Mustard Dijon", "Mayonnaise", "Relish", "Salsa",
  "Coconut Milk Canned", "Evaporated Milk", "Sweetened Condensed Milk", "Pumpkin Puree",
  "Chipotle in Adobo", "Green Chiles", "Olives", "Capers", "Pickles", "Pickled Jalapeños",
  "Marinara Sauce", "Alfredo Sauce", "Pesto", "Curry Paste", "Fish Sauce", "Worcestershire",
  "Vanilla Extract", "Almond Extract", "Salt", "Black Pepper", "Garlic Powder", "Onion Powder",
  "Paprika", "Cumin", "Chili Powder", "Oregano", "Basil Dried", "Cinnamon", "Nutmeg",
  "Bay Leaves", "Red Pepper Flakes", "Italian Seasoning", "Taco Seasoning", "Ranch Mix",
  "Breadcrumbs", "Crackers", "Baking Soda", "Baking Powder", "Yeast", "Cornstarch",
  "Cocoa Powder", "Chocolate Chips", "Dried Cranberries", "Raisins", "Dried Apricots",
  "Sun-Dried Tomatoes", "Dried Basil", "Bouillon Cubes", "Gelatin", "Pectin",
  "Marshmallows", "Graham Cracker Crust", "Pie Filling Cherry", "Pie Filling Apple",
  "Canned Pineapple", "Canned Peaches", "Canned Pears", "Applesauce", "Coconut Flakes",
  "Slivered Almonds", "Walnut Halves", "Pecans", "Cashews", "Mixed Nuts", "Peanuts",
  "Sunflower Seeds", "Pumpkin Seeds", "Chia Seeds", "Flax Seed", "Sesame Seeds",
];

const FROZEN_100: string[] = [
  "Frozen Mixed Vegetables", "Frozen Broccoli", "Frozen Peas", "Frozen Corn", "Frozen Green Beans",
  "Frozen Spinach", "Frozen Cauliflower", "Frozen Stir Fry Vegetables", "Frozen Berry Mix",
  "Frozen Strawberries", "Frozen Blueberries", "Frozen Mango", "Frozen Pineapple", "Frozen Peaches",
  "Frozen Pizza", "Frozen Cheese Pizza", "Frozen Pepperoni Pizza", "Frozen Veggie Pizza",
  "Ice Cream Vanilla", "Ice Cream Chocolate", "Ice Cream Strawberry", "Ice Cream Mint Chip",
  "Frozen Waffles", "Frozen Pancakes", "Frozen French Toast", "Frozen Hash Browns",
  "Frozen Tater Tots", "Frozen Onion Rings", "Frozen French Fries", "Frozen Sweet Potato Fries",
  "Frozen Chicken Nuggets", "Frozen Fish Sticks", "Frozen Salmon Fillets", "Frozen Shrimp",
  "Frozen Tilapia", "Frozen Mahi", "Frozen Burger Patties", "Frozen Meatballs",
  "Frozen Lasagna", "Frozen Mac and Cheese", "Frozen Pot Pies", "Frozen Burritos",
  "Frozen Taquitos", "Frozen Egg Rolls", "Frozen Dumplings", "Frozen Pierogies",
  "Frozen Puff Pastry", "Frozen Pie Crust", "Frozen Phyllo", "Frozen Cookie Dough",
  "Frozen Puff Pastry Sheets", "Frozen Dessert Bars", "Frozen Fruit Bars", "Frozen Yogurt",
  "Frozen Sorbet", "Frozen Gelato", "Frozen Smoothie Blend", "Frozen Acai", "Frozen Edamame",
  "Frozen Shelled Edamame", "Frozen Brussels Sprouts", "Frozen Asparagus", "Frozen Artichoke Hearts",
  "Frozen Okra", "Frozen Lima Beans", "Frozen Black-Eyed Peas", "Frozen Collard Greens",
  "Frozen Kale", "Frozen Butternut Squash", "Frozen Mashed Potatoes", "Frozen Dinner Entrees",
  "Frozen Breakfast Sandwiches", "Frozen Bagels", "Frozen Garlic Bread", "Frozen Rolls",
  "Frozen Cinnamon Rolls", "Frozen Croissants", "Frozen Puff Pastry Appetizers",
  "Frozen Spanakopita", "Frozen Samosas", "Frozen Spring Rolls", "Frozen Calzones",
  "Frozen Quesadillas", "Frozen Enchiladas", "Frozen Fajita Vegetables", "Frozen Riced Cauliflower",
  "Frozen Zucchini Noodles", "Frozen Spiralized Vegetables", "Frozen Quinoa Blend",
  "Frozen Rice Pilaf", "Frozen Risotto", "Frozen Pad Thai", "Frozen Stir Fry",
  "Frozen Orange Chicken", "Frozen General Tso", "Frozen Teriyaki", "Frozen Coconut Shrimp",
  "Frozen Crab Cakes", "Frozen Lobster Tails", "Frozen Scallops", "Frozen Calamari",
  "Frozen Breaded Mushrooms", "Frozen Mozzarella Sticks", "Frozen Jalapeño Poppers",
  "Frozen Potato Skins", "Frozen Mini Tacos", "Frozen Pizza Rolls", "Frozen Bagel Bites",
  "Frozen Hot Pockets", "Frozen Lean Cuisine", "Frozen Healthy Choice", "Frozen Amy's",
  "Frozen Organic Vegetables", "Frozen Organic Fruit", "Frozen Keto Meals",
];

const DELI_100: string[] = [
  "Sliced Turkey Breast", "Sliced Ham", "Sliced Roast Beef", "Sliced Chicken Breast",
  "Sliced Salami", "Sliced Pepperoni", "Sliced Bologna", "Sliced Pastrami", "Sliced Corned Beef",
  "Sliced Prosciutto", "Sliced Capicola", "Sliced Mortadella", "Sliced Genoa Salami",
  "Sliced Cheddar", "Sliced Swiss", "Sliced Provolone", "Sliced American", "Sliced Pepper Jack",
  "Sliced Colby Jack", "Sliced Muenster", "Sliced Gouda", "Sliced Havarti", "Hummus Classic",
  "Hummus Roasted Garlic", "Hummus Roasted Red Pepper", "Hummus Everything", "Baba Ganoush",
  "Tzatziki", "Spinach Artichoke Dip", "Seven Layer Dip", "Guacamole", "Salsa Fresca",
  "Potato Salad", "Coleslaw", "Macaroni Salad", "Pasta Salad", "Egg Salad", "Tuna Salad",
  "Chicken Salad", "Greek Salad", "Antipasto", "Olive Bar Mix", "Pickled Vegetables",
  "Jalapeño Poppers", "Stuffed Peppers", "Deviled Eggs", "Cheese Board", "Charcuterie Board",
  "Deli Rotisserie Chicken", "Deli Fried Chicken", "Deli Meat Loaf", "Deli Pulled Pork",
  "Deli Brisket", "Deli Ribs", "Deli Wings", "Deli Subs", "Deli Wraps", "Deli Sandwiches",
  "Deli Pinwheels", "Deli Roll Ups", "Deli Skewers", "Deli Fruit Tray", "Deli Veggie Tray",
  "Deli Cheese Tray", "Deli Party Platter", "Deli Sandwich Platter", "Deli Wrap Platter",
  "Deli Pinwheel Platter", "Deli Fruit Salad", "Deli Pasta Salad", "Deli Green Salad",
  "Deli Caesar Salad", "Deli Cobb Salad", "Deli Chef Salad", "Deli Garden Salad",
  "Deli Kale Salad", "Deli Quinoa Salad", "Deli Tabouli", "Deli Couscous", "Deli Orzo Salad",
  "Deli Bean Salad", "Deli Three Bean", "Deli Edamame Salad", "Deli Sushi", "Deli Poke",
  "Deli Ceviche", "Deli Shrimp Cocktail", "Deli Crab Salad", "Deli Lobster Salad",
  "Deli Tuna Poke", "Deli Salmon Poke", "Deli Kimbap", "Deli Onigiri", "Deli Inari",
  "Deli California Roll", "Deli Spicy Tuna Roll", "Deli Dragon Roll", "Deli Philadelphia Roll",
  "Deli Veggie Roll", "Deli Tempura Roll", "Deli Rainbow Roll", "Deli Catering Tray",
  "Deli Breakfast Sandwiches", "Deli Breakfast Burrito", "Deli Breakfast Bowl",
  "Deli Omelet", "Deli Quiche", "Deli Frittata", "Deli Breakfast Potatoes",
  "Deli Bacon", "Deli Sausage", "Deli Biscuits", "Deli Gravy", "Deli Breakfast Platter",
];

const SNACKS_100: string[] = [
  "Potato Chips", "Tortilla Chips", "Corn Chips", "Pita Chips", "Pretzels", "Popcorn",
  "Cheese Popcorn", "Caramel Popcorn", "Mixed Nuts", "Trail Mix", "Peanuts", "Cashews",
  "Almonds", "Pistachios", "Sunflower Seeds", "Pumpkin Seeds", "Granola Bars", "Protein Bars",
  "Energy Bars", "Fruit Snacks", "Fruit Leather", "Dried Fruit", "Veggie Chips", "Kale Chips",
  "Banana Chips", "Plantain Chips", "Crackers", "Cheese Crackers", "Graham Crackers",
  "Rice Cakes", "Rice Crackers", "Popcorn Cakes", "Cheese Puffs", "Pirate's Booty",
  "Goldfish", "Animal Crackers", "Teddy Grahams", "Cookies", "Brownie Bites",
  "Mini Muffins", "Candy Chocolate", "Candy Gummy", "Candy Hard", "Chocolate Bar",
  "Dark Chocolate", "Milk Chocolate", "Peanut Butter Cups", "Chocolate Covered Nuts",
  "Chocolate Covered Raisins", "Licorice", "Jelly Beans", "M&Ms", "Skittles", "Starburst",
  "Sour Patch Kids", "Haribo Gummy Bears", "Swedish Fish", "Twizzlers", "Reese's",
  "Snickers", "Kit Kat", "Twix", "Hershey's", "Milk Duds", "Whoppers", "Raisinets",
  "Tootsie Rolls", "Junior Mints", "York Peppermint", "Almond Joy", "Mounds",
  "Beef Jerky", "Turkey Jerky", "Meat Sticks", "String Cheese", "Cheese Cubes",
  "Pepperoni Sticks", "Salami Sticks", "Hummus and Pretzels", "Crackers and Cheese",
  "Apple Sauce Pouches", "Yogurt Pouches", "Squeeze Pouch Fruit", "Veggie Straws",
  "Sweet Potato Chips", "Bean Chips", "Lentil Chips", "Quinoa Chips", "Keto Snacks",
  "Low Carb Crackers", "Sugar-Free Candy", "Dark Chocolate Almonds", "Dried Mango",
  "Dried Pineapple", "Dried Apricots", "Dried Figs", "Dried Dates", "Dried Coconut",
  "Freeze-Dried Fruit", "Freeze-Dried Strawberries", "Coconut Chips", "Seaweed Snacks",
  "Wasabi Peas", "Sesame Sticks", "Bugles", "Combos", "Chex Mix", "Gardetto's",
  "Nutella and Breadsticks", "Cookie Dough Bites", "Mini Oreos", "Nutter Butters",
  "Chips Ahoy", "Fig Newtons", "Belvita", "Kind Bars", "Larabars", "Clif Bars",
  "RXBAR", "Quest Bars", "Perfect Bar", "That's It Bars", "Smart Sweets",
  "Popcorners", "Boom Chicka Pop", "SkinnyPop", "Lesser Evil", "Hippeas", "Pirate's Booty",
];

export const ITEM_NAMES_BY_CATEGORY = {
  Produce: padTo100(PRODUCE_100, "Produce"),
  "Dairy & Eggs": padTo100(DAIRY_EGGS_100, "Dairy & Eggs"),
  Beverages: padTo100(BEVERAGES_100, "Beverages"),
  Bakery: padTo100(BAKERY_100, "Bakery"),
  Pantry: padTo100(PANTRY_100, "Pantry"),
  Frozen: padTo100(FROZEN_100, "Frozen"),
  Deli: padTo100(DELI_100, "Deli"),
  Snacks: padTo100(SNACKS_100, "Snacks"),
} as const
